window.LUNAR_DATA = {
  version: "0.2.0",
  defaults: {
    format: "oneOffSmall",
    faction: "NASA",
    oxygen: 12,
    credits: 15
  },
  formats: [
    { id: "oneOffSmall", name: "One-off small", oxygen: 12, credits: 15, mode: "oneOff" },
    { id: "oneOffMedium", name: "One-off medium", oxygen: 20, credits: 25, mode: "oneOff" },
    { id: "oneOffLarge", name: "One-off large", oxygen: 32, credits: 40, mode: "oneOff" },
    { id: "campaignStart", name: "Campaign start", oxygen: 12, credits: 12, mode: "campaignStart" },
    { id: "custom", name: "Custom", oxygen: null, credits: null, mode: "custom" }
  ],
  factions: [
    { id: "NASA", name: "NASA", theme: "blue" },
    { id: "USSR", name: "USSR", theme: "red" },
    { id: "Unaligned", name: "Mixed / Unaligned", theme: "neutral" }
  ],
  trainingGames: [
    {
      id: "rulebook-mining-demo",
      title: "Пробная партия: Mining Crews",
      source: "Rulebook example crews, pages 16-17",
      note: "Две готовые команды из примеров правил: по 3 модели, 12 Oxygen и 27 кредитов снаряжения на сторону.",
      teams: [
        {
          id: "nasa-mining-crew",
          side: "NASA",
          title: "NASA Mining Crew",
          roster: {
            name: "NASA Mining Crew",
            format: "custom",
            faction: "NASA",
            oxygenBudget: 12,
            budget: 27,
            units: [
              {
                unitId: "nasa-commander-core",
                equipmentIds: ["core-markham-s11"]
              },
              {
                unitId: "nasa-combat-core",
                equipmentIds: ["core-heavy-mining-drill", "core-resin-patch"]
              },
              {
                unitId: "nasa-generalist-core",
                equipmentIds: ["core-geology-hammer", "core-improvised-weapon"]
              }
            ]
          }
        },
        {
          id: "ussr-mining-crew",
          side: "USSR",
          title: "CCCP Mining Crew",
          roster: {
            name: "CCCP Mining Crew",
            format: "custom",
            faction: "USSR",
            oxygenBudget: 12,
            budget: 27,
            units: [
              {
                unitId: "ussr-commander-core",
                equipmentIds: ["core-mass-shotgun"]
              },
              {
                unitId: "ussr-combat-core",
                equipmentIds: ["core-heavy-mining-drill", "core-resin-patch"]
              },
              {
                unitId: "ussr-generalist-core",
                equipmentIds: ["core-geology-hammer", "core-improvised-weapon"]
              }
            ]
          }
        }
      ]
    }
  ],
  units: [
    {
      id: "nasa-commander-core",
      name: "NASA Astronaut",
      subtitle: "Commander",
      faction: "NASA",
      role: "Commander",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/NASA Commander.png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 3,
      competency: 2,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Commander", "Astronaut"],
      text: "Stringent Training: Other friendly units within 4 inches of this unit receive a +1 bonus to their competency rolls. The bonus cannot be applied to the Commander's competency rolls."
    },
    {
      id: "nasa-combat-core",
      name: "NASA Astronaut",
      subtitle: "Combat Specialist",
      faction: "NASA",
      role: "Combat Specialist",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/NASA Combat Spec.png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 3,
      competency: 2,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Combat Specialist", "Astronaut"],
      text: "Combat Training: After using any ranged weapon, this unit can freely adjust its facing. Boot Camp: The first time this unit is hit each round, it can redirect the incoming attack to any unit within 2 inches. Damage is resolved against the newly targeted unit. This ability can only be used for a single hit each round."
    },
    {
      id: "nasa-generalist-core",
      name: "NASA Astronaut",
      subtitle: "Generalist",
      faction: "NASA",
      role: "Generalist",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/NASA Generalist.png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 3,
      competency: null,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Generalist", "Astronaut"],
      text: "A baseline NASA astronaut with no printed special ability."
    },
    {
      id: "ussr-commander-core",
      name: "USSR Cosmonaut",
      subtitle: "Commander",
      faction: "USSR",
      role: "Commander",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/USSR Commander.png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 3,
      competency: 2,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Commander", "Astronaut"],
      text: "For the Motherland!: During this Commander's activation, any friendly unit within 4 inches may take an additional action, even if they have already used all their available actions. This extra action does not consume any oxygen."
    },
    {
      id: "ussr-combat-core",
      name: "USSR Cosmonaut",
      subtitle: "Combat Specialist",
      faction: "USSR",
      role: "Combat Specialist",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/USSR Combat Spec.png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 3,
      competency: 2,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Combat Specialist", "Astronaut"],
      text: "Combat Training: After dealing damage, this unit may perform a free move action. Soviet Strike: During a close combat push attack, this unit doubles their push distance result."
    },
    {
      id: "ussr-generalist-core",
      name: "USSR Cosmonaut",
      subtitle: "Generalist",
      faction: "USSR",
      role: "Generalist",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/USSR Generalist.png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 2,
      competency: null,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Generalist", "Astronaut"],
      text: "A baseline USSR cosmonaut with no printed special ability."
    },
    {
      id: "nasa-generalist-zvezda",
      name: "NASA Astronaut",
      subtitle: "Generalist",
      faction: "NASA",
      role: "Generalist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/NASA (1).png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 3,
      competency: null,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Generalist", "Astronaut"],
      text: "A baseline NASA astronaut from the Attack on Zvezda expansion."
    },
    {
      id: "nasa-medical-zvezda",
      name: "NASA Astronaut",
      subtitle: "Medical Specialist",
      faction: "NASA",
      role: "Medical Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/NASA (2).png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 3,
      competency: 1,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Specialist", "Astronaut"],
      text: "Medical Training: A resin patch can be used twice by this unit before discarding. When within 3 inches from a unit that is OoA, that unit may make a free crawl action in any direction. May not use ranged weapons."
    },
    {
      id: "nasa-tech-zvezda",
      name: "NASA Astronaut",
      subtitle: "Tech Specialist",
      faction: "NASA",
      role: "Tech Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/NASA (3).png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 2,
      competency: 1,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Specialist", "Astronaut"],
      text: "Technical Training: When within 3 inches from an allied unmanned unit, the unmanned unit may make a free movement action at no cost. When in base-to-base contact with an unmanned unit this unit may reroll a failed repair action once per activation. May not use rare weapons."
    },
    {
      id: "nasa-mission-zvezda",
      name: "NASA Astronaut",
      subtitle: "Mission Specialist",
      faction: "NASA",
      role: "Mission Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/NASA (4).png",
      mass: 4,
      massTrack: [4, 5, 6, 7, 8, 9],
      overburdenAt: 8,
      oxygen: 4,
      move: 2,
      competency: 1,
      defense: 4,
      integrity: 4,
      keywords: ["USA", "Specialist", "Astronaut"],
      text: "Basic Training: +2 to any mining actions. +2 to any interact actions."
    },
    {
      id: "ussr-medical-zvezda",
      name: "USSR Cosmonaut",
      subtitle: "Medical Specialist",
      faction: "USSR",
      role: "Medical Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/USSR (1).png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 3,
      competency: 1,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Specialist", "Astronaut"],
      text: "Medical Training: Once per game this unit may choose any OoA unit and force them to activate as normal with their full oxygen value. After this activation, the unit is immediately removed from play. Any enemy unit within 1 inch cannot use a resin patch on themselves. May not use ranged weapons."
    },
    {
      id: "ussr-tech-zvezda",
      name: "USSR Cosmonaut",
      subtitle: "Tech Specialist",
      faction: "USSR",
      role: "Tech Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/USSR (2).png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 2,
      competency: 1,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Specialist", "Astronaut"],
      text: "Technical Training: An unmanned rover within 3 inches of this unit may reroll any action, once per activation. May not use rare weapons."
    },
    {
      id: "ussr-mission-zvezda",
      name: "USSR Cosmonaut",
      subtitle: "Mission Specialist",
      faction: "USSR",
      role: "Mission Specialist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/USSR (3).png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 2,
      competency: 1,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Specialist", "Astronaut"],
      text: "Basic Training: +2 to any mining actions. +2 to any interact actions."
    },
    {
      id: "ussr-generalist-zvezda",
      name: "USSR Cosmonaut",
      subtitle: "Generalist",
      faction: "USSR",
      role: "Generalist",
      set: "Attack on Zvezda",
      img: "assets/cards/zvezda/USSR (4).png",
      mass: 5,
      massTrack: [5, 6, 7, 8, 9, 10],
      overburdenAt: 9,
      oxygen: 4,
      move: 2,
      competency: null,
      defense: 5,
      integrity: 4,
      keywords: ["USSR", "Generalist", "Astronaut"],
      text: "A baseline USSR cosmonaut from the Attack on Zvezda expansion."
    }
  ],
  equipment: [
    {
      id: "core-geology-hammer",
      name: "Geology Hammer",
      type: "weapon",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Hammer.png",
      mass: 1,
      credits: 2,
      rarity: "Common",
      traits: ["Common", "Melee", "Mining"],
      attacks: ["Piercing 4+", "Range M"],
      text: "Jack Schmitt's Request: this weapon is thrown with a straight 2d6 roll, and item mass is not subtracted from the result. Mining: +1 to mining action comp rolls."
    },
    {
      id: "core-heavy-mining-drill",
      name: "Heavy Mining Drill",
      type: "weapon",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Drill.png",
      mass: 3,
      credits: 10,
      rarity: "Common",
      traits: ["Common", "Two-Handed", "Mining"],
      attacks: ["Piercing 6+", "Range 1"],
      text: "Power Trigger: this item gives +4 to mining action comp rolls."
    },
    {
      id: "core-improvised-weapon",
      name: "Improvised Weapon",
      type: "weapon",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Improvised Weapon.png",
      mass: 1,
      credits: 1,
      rarity: "Common",
      traits: ["Common", "Melee"],
      attacks: ["Blunt 6+", "Range M"],
      text: "A cheap close combat option for emergency fights."
    },
    {
      id: "core-markham-s11",
      name: "Markham S11",
      type: "weapon",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Markham S11.png",
      mass: 2,
      credits: 12,
      rarity: "Rare",
      traits: ["Rare", "Ranged", "Sidearm"],
      attacks: ["Piercing 5+", "Range 8", "Ammo 4"],
      text: "A compact ranged weapon with piercing damage and sidearm handling."
    },
    {
      id: "core-mass-shotgun",
      name: "Mass Shotgun",
      type: "weapon",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Mass Shotgun.png",
      mass: 3,
      credits: 12,
      rarity: "Common",
      traits: ["Common", "Ranged", "Two-Handed"],
      attacks: ["Blunt 8+", "Range 10", "Ammo 4"],
      text: "A heavy close-to-mid range weapon."
    },
    {
      id: "core-resin-patch",
      name: "Resin Patch",
      type: "item",
      set: "Lunar 2 Player Starter",
      img: "assets/cards/core/Resin Patch.png",
      mass: 0,
      credits: 2,
      rarity: "Common",
      traits: ["Common", "Single Use"],
      attacks: [],
      text: "A survival patch used to recover or stabilize astronauts. Check the card for the exact timing."
    },
    {
      id: "exp-explosive-charge",
      name: "Explosive Charge",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-01.png",
      mass: 2,
      credits: 5,
      rarity: "Common",
      traits: ["Common", "Single Use", "Explosive"],
      attacks: ["Piercing 5+"],
      text: "Big Boom: when detonated, any unit within 2 inches immediately takes a +5 piercing hit."
    },
    {
      id: "exp-proximity-charge",
      name: "Proximity Charge",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-02.png",
      mass: 2,
      credits: 5,
      rarity: "Rare",
      traits: ["Rare", "Single Use", "Explosive"],
      attacks: ["Piercing 6+"],
      text: "Tripwire: detonates when an enemy explosive action, item, or resource comes within 1 inch. Any unit within 2 inches immediately takes a +6 hit."
    },
    {
      id: "exp-ultrasonic-mining-pick",
      name: "Ultrasonic Mining Pick",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-03.png",
      mass: 1,
      credits: 8,
      rarity: "Common",
      traits: ["Common", "Mining", "Melee", "Cutting"],
      attacks: ["Piercing 6+", "Range M"],
      text: "Tethered: requires an external power source. Power Trigger: +2 to mining comp rolls."
    },
    {
      id: "exp-s8-laser-pistol",
      name: "S8-Laser Pistol",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-04.png",
      mass: 2,
      credits: 3,
      rarity: "Common",
      traits: ["Common", "Ranged", "Blinding"],
      attacks: ["Blinding", "Range 14"],
      text: "This weapon does no damage. It applies the blinded status on a hit. If fired at a range-finding camera, it cannot be used during that unit's next activation."
    },
    {
      id: "exp-net-rifle",
      name: "Net Rifle",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-05.png",
      mass: 2,
      credits: 8,
      rarity: "Common",
      traits: ["Common", "Ranged"],
      attacks: ["Blunt 5+", "Range 8", "Ammo 2"],
      text: "Secure Payload: if successfully hit, any unit within 1 inch of the hit unit also becomes entangled."
    },
    {
      id: "exp-m67-rifle",
      name: "M67 Rifle",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-06.png",
      mass: 3,
      credits: 15,
      rarity: "Rare",
      traits: ["Rare", "Ranged", "Two-Handed"],
      attacks: ["Piercing 6+", "Range 14", "Ammo 3"],
      text: "A rare two-handed rifle with long reach."
    },
    {
      id: "exp-targeting-camera",
      name: "Targeting Camera",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-07.png",
      mass: 1,
      credits: 3,
      rarity: "Common",
      traits: ["Common"],
      attacks: [],
      text: "Rangefinder: allows pre-measuring for this unit and any ally units within 2 inches."
    },
    {
      id: "exp-enhanced-cooling-suit",
      name: "Enhanced Cooling Suit",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-08.png",
      mass: 1,
      credits: 9,
      rarity: "Common",
      traits: ["Common"],
      attacks: [],
      text: "Nice and Cool: efficient tubing and cooling systems keep you cool. Gives bonuses against fatigue and repeated actions; check the card for exact wording."
    },
    {
      id: "exp-kevlar-outer-suit",
      name: "Kevlar Outer-Suit",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-09.png",
      mass: 1,
      credits: 15,
      rarity: "Rare",
      traits: ["Rare"],
      attacks: [],
      text: "Tough Mother: ignore two hazard dice results per combat resolution."
    },
    {
      id: "exp-blast-shield",
      name: "Blast Shield",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-10.png",
      mass: 2,
      credits: 10,
      rarity: "Common",
      traits: ["Common", "Two-Handed"],
      attacks: [],
      text: "Unwieldy: -1 to unit mobility. Defensive Position: if hit with a ranged weapon from the front arc, ignore one hazard die per combat resolution. Shield Wall: friendly units in contact gain heavy cover."
    },
    {
      id: "exp-ceramic-plating",
      name: "Ceramic Plating",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-11.png",
      mass: 2,
      credits: 5,
      rarity: "Common",
      traits: ["Common"],
      uses: 2,
      attacks: [],
      text: "Close One: ignore one hazard dice result."
    },
    {
      id: "exp-improvised-buckler",
      name: "Improvised Buckler",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-12.png",
      mass: 2,
      credits: 6,
      rarity: "Common",
      traits: ["Common", "Multi Use"],
      uses: 3,
      attacks: [],
      text: "Defensive Position and Small Shield Wall defensive effects. Check the card for the full cover wording."
    },
    {
      id: "exp-invasive-adrenaline",
      name: "Invasive Adrenaline",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-13.png",
      mass: 0,
      credits: 2,
      rarity: "Common",
      traits: ["Common", "Single Use"],
      attacks: [],
      text: "Make a Hole: when used on a unit, it gains oxygen and rolls hazard dice. Survival Instinct: a unit may use the item while prone."
    },
    {
      id: "exp-lunar-caltrops",
      name: "Lunar Caltrops",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-14.png",
      mass: 1,
      credits: 6,
      rarity: "Common",
      traits: ["Common", "Multi Use"],
      uses: 2,
      attacks: ["Range 5"],
      text: "Horseshoes and hand grenades: place a 3 inch circle on the target point. Units are grounded and must roll hazard dice when moving through the area."
    },
    {
      id: "exp-ballistic-knife",
      name: "Ballistic Knife",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-15.png",
      mass: 1,
      credits: 8,
      rarity: "Rare",
      traits: ["Rare", "Melee", "Ranged", "Cutting"],
      attacks: ["Piercing 6+", "Range M", "Range 6", "Ammo 2"],
      text: "Spring Loaded: fires as a ranged attack with 6 inch range. Can no longer be used as a cutting item or close combat weapon after firing."
    },
    {
      id: "exp-usa-flag",
      name: "Flag",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-16.png",
      faction: "NASA",
      mass: 2,
      credits: 9,
      rarity: "Rare",
      traits: ["Rare", "Melee"],
      attacks: ["Piercing 4+", "Range M"],
      text: "For All Mankind: may force one reroll on any no hit roll. Watch That Air Ripple: gain +1 Comp while engaged in combat."
    },
    {
      id: "exp-ussr-flag",
      name: "Flag",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-17.png",
      faction: "USSR",
      mass: 2,
      credits: 9,
      rarity: "Rare",
      traits: ["Rare", "Melee"],
      attacks: ["Piercing 4+", "Range M"],
      text: "For All Mankind: may force one reroll on any no hit roll. Watch That Air Ripple: gain +1 Comp while engaged in combat."
    },
    {
      id: "exp-impact-drill",
      name: "Impact Drill",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-18.png",
      mass: 1,
      credits: 10,
      rarity: "Common",
      traits: ["Common", "Melee"],
      attacks: ["Piercing 5+"],
      text: "Improved Haptics Sensation: this unit gains an additional +3 to mining action comp rolls."
    },
    {
      id: "exp-improvised-mass-shotgun",
      name: "Improvised Mass Shotgun",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-19.png",
      mass: 3,
      credits: 9,
      rarity: "Common",
      traits: ["Common", "Ranged", "Two-Handed"],
      attacks: ["Blunt 6+", "Range 8", "Ammo 2"],
      text: "Improvised: on a failed comp roll while firing, this weapon is clogged and cannot be fired again."
    },
    {
      id: "exp-ils-glove",
      name: "ILS Glove MkIV",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-20.png",
      mass: 0,
      credits: 10,
      rarity: "Common",
      traits: ["Common"],
      attacks: [],
      text: "Improved Haptics Sensation: this unit gains an additional +2 to item comp rolls."
    },
    {
      id: "exp-adhesive-rifle",
      name: "Adhesive Rifle",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-21.png",
      mass: 2,
      credits: 8,
      rarity: "Common",
      traits: ["Common", "Ranged"],
      attacks: ["Range 8", "Ammo 3"],
      text: "Sticky Goo: on a successful comp roll this weapon fires sticky goo in a 1 inch wide line. Units in the line are entangled."
    },
    {
      id: "exp-reserve-tank",
      name: "Reserve Tank",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-22.png",
      mass: 1,
      credits: 8,
      rarity: "Rare",
      traits: ["Rare"],
      uses: 3,
      attacks: [],
      text: "Breath of Fresh Air: this unit gains one extra oxygen per round."
    },
    {
      id: "exp-lunar-flare",
      name: "Lunar Flare",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-23.png",
      mass: 1,
      credits: 3,
      rarity: "Common",
      traits: ["Common", "Single Use"],
      attacks: [],
      text: "Strike the Match: once deployed, any unit within 3 inches is blinded until its next activation. Burning: if hit by this item on a successful throw, that unit immediately rolls one hazard die."
    },
    {
      id: "exp-m82a-00",
      name: "M82A-00",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-24.png",
      mass: 4,
      credits: 22,
      rarity: "Rare",
      traits: ["Rare", "Ranged", "Two-Handed", "Big Kick"],
      attacks: ["Piercing 10+", "Range 20", "Ammo 3"],
      text: "Through and Through: when fired, this weapon hits up to two targets in a straight line within 20 inches. Like a Truck: any units hit are immediately moved 2 inches."
    },
    {
      id: "exp-resin-patch",
      name: "Resin Patch",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-25.png",
      mass: 0,
      credits: 2,
      rarity: "Common",
      traits: ["Common", "Single Use"],
      attacks: [],
      text: "Plug the Hole: during your turn this unit can spend one oxygen to regain one skill integrity. Survival Instinct: may be used while the unit is prone."
    },
    {
      id: "exp-comm-jamm",
      name: "Comm-Jamm",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-26.png",
      mass: 1,
      credits: 9,
      rarity: "Rare",
      traits: ["Rare"],
      attacks: ["Range 8"],
      text: "Max Headroom: a unit with this jammer may target a unit and roll a comp check. On a failed comp check, apply the result to the nearest friendly unit instead."
    },
    {
      id: "exp-auto-dim-visor",
      name: "Auto-dim Visor",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-27.png",
      mass: 1,
      credits: 3,
      rarity: "Common",
      traits: ["Common"],
      attacks: [],
      text: "Fancy Glass: units with this item cannot be blinded."
    },
    {
      id: "exp-shrapnel-shotgun",
      name: "Shrapnel Shotgun",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-28.png",
      mass: 3,
      credits: 18,
      rarity: "Rare",
      traits: ["Rare", "Ranged", "Two-Handed"],
      attacks: ["Piercing 6+", "Range 6", "Ammo 3"],
      text: "Buck Shot: fires in a 1 inch wide line and hits any units within range unless they have heavy cover from the shooter."
    },
    {
      id: "exp-standard-knife",
      name: "Standard Knife",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-29.png",
      mass: 1,
      credits: 6,
      rarity: "Common",
      traits: ["Common", "Melee", "Cutting"],
      attacks: ["Piercing 6+", "Range M"],
      text: "A common cutting melee weapon."
    },
    {
      id: "exp-survival-rifle",
      name: "Survival Rifle",
      type: "weapon",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-30.png",
      mass: 2,
      credits: 12,
      rarity: "Common",
      traits: ["Common", "Ranged", "Sidearm", "Single Use"],
      attacks: ["Shotgun 4+", "Range 5", "Ammo 2", "Rifle 6+", "Range 8", "Ammo 1"],
      text: "Spice of Life: this gun has three single-use barrels. Buck Shot: shotgun shells fire in a 1 inch wide line. Slug Use: use for a single shot."
    },
    {
      id: "exp-duct-tape",
      name: "Duct Tape",
      type: "item",
      set: "Expanded Weapon and Item Deck",
      img: "assets/cards/items/Core weapon and Item - Digital-31.png",
      mass: 0,
      credits: 1,
      rarity: "Common",
      traits: ["Common", "Multi Use"],
      uses: 3,
      attacks: [],
      text: "Use one oxygen to reroll a D6. On 12, or 3, oxygen or suit integrity point; on 4, 5, 6, repair fails. Units do not gain oxygen back until the next turn."
    }
  ],
  rules: [
    {
      id: "core-oxygen",
      title: "Oxygen",
      category: "core",
      tags: ["oxygen", "action", "round"],
      body: "Oxygen is the action economy resource shown on unit cards. Several cards spend, add, or preserve oxygen. Use the printed card text as the source of truth for exact timing."
    },
    {
      id: "core-mass",
      title: "Mass",
      category: "core",
      tags: ["mass", "equipment", "loadout"],
      body: "A unit's current mass is its base mass plus equipped items, resources, and mission cards. Red boxes on the mass bar give Overburdened tokens."
    },
    {
      id: "core-credits",
      title: "Credits",
      category: "core",
      tags: ["credits", "budget", "items"],
      body: "Credits buy crew-owned equipment and weapons. One-off recommendations are 15 credits for 12 oxygen, 25 credits for 20 oxygen, and 40+ credits for 32 oxygen."
    },
    {
      id: "core-rare",
      title: "Rare Items",
      category: "core",
      tags: ["rare", "deck", "equipment"],
      body: "Rare items and rare weapons may be used by Commanders and Specialists. Generalists may not use rare items or rare weapons. Campaign crews may not start with rare items."
    },
    {
      id: "crew-building",
      title: "Building Your Crew",
      category: "core",
      tags: ["crew", "oxygen", "credits", "one-off", "campaign"],
      body: "Crews are built with two values: total oxygen from units and total credits spent on gear. Small one-off games use 12 oxygen and 15 credits, medium 20 oxygen and 25 credits, large 32 oxygen and 40+ credits."
    },
    {
      id: "crew-ranks",
      title: "Crew Ranks",
      category: "core",
      tags: ["commander", "specialist", "generalist", "unmanned", "ratio"],
      body: "A crew can have only one Commander. Specialists are limited to one plus one additional Specialist for every two Generalists. Campaign start is stricter: one Commander and one Specialist maximum. Generalists are unlimited and cannot use rare gear."
    },
    {
      id: "crew-faction",
      title: "Faction And Unaligned Crews",
      category: "core",
      tags: ["faction", "unaligned", "mixed", "commander", "boon"],
      body: "Crews may mix units and items, but mixed crews count as unaligned. Unaligned crews may not use commander special rules or faction-specific items."
    },
    {
      id: "status-overburdened",
      title: "Overburdened",
      category: "core",
      tags: ["status", "mass", "mobility", "climb", "jump"],
      body: "When current mass reaches red boxes on the unit mass bar, the unit gains one Overburdened token per red mass point. Each token reduces mobility by 1. Overburdened units may not climb or jump."
    },
    {
      id: "trait-two-handed",
      title: "Two-Handed",
      category: "equipment",
      tags: ["trait", "two-handed", "weapon", "item"],
      body: "A unit may only carry one Two-Handed weapon or item at a time."
    },
    {
      id: "campaign-start",
      title: "Campaign Start",
      category: "core",
      tags: ["campaign", "start", "12 oxygen", "12 credits", "rare"],
      body: "A campaign crew starts with 12 oxygen and 12 credits. It may not start with rare items and may only start with one Commander and one Specialist."
    },
    {
      id: "campaign-storage",
      title: "Storage Room",
      category: "core",
      tags: ["campaign", "storage", "gear", "equipment", "single use"],
      body: "Gear bought with credits belongs to the crew storage room and can be assigned before a mission. Non-consumable gear can return to storage; single-use items must be bought again after use."
    },
    {
      id: "campaign-resupply",
      title: "Resupply Shuttles",
      category: "core",
      tags: ["campaign", "shuttle", "rare", "capacity", "travel"],
      body: "Rare items are acquired through resupply shuttles. Shuttles have credit cost, oxygen/credit cargo capacity, and travel duration before cargo reaches the crew."
    },
    {
      id: "campaign-icons",
      title: "Lunar Icons",
      category: "unit",
      tags: ["campaign", "icons", "upkeep", "dealbreaker", "settlement"],
      body: "Lunar Icons are campaign recruits with requirements, acquisition cost, upkeep, settlement boons, dealbreakers, and sometimes playable unit profiles with free icon gear."
    },
    {
      id: "campaign-resources",
      title: "Resources And Postgame Credits",
      category: "core",
      tags: ["campaign", "resource", "postgame", "credits", "reward"],
      body: "Resource tokens are traded during postgame using the resource table. Mission rewards can also grant extra credits, rare purchase options, or special recovery effects."
    },
    {
      id: "mission-list",
      title: "Core Missions",
      category: "core",
      tags: ["mission", "scenario", "deployment", "resource nodes", "postgame"],
      body: "The core book includes Capture the Cache, Site 74-B, Defend the Settlement, Seismic Fissure, Shuttle Graveyard, I Called Dibs, and Unstable Relations. Each mission defines turns, deployment, hazards, win conditions, resources, and postgame credits."
    },
    {
      id: "environmental-hazards",
      title: "Environmental Hazards",
      category: "core",
      tags: ["hazard", "meteor", "solar storm", "moonquake", "shuttle explosion", "sink hole"],
      body: "Advanced setup can roll 2D6 for environmental hazards such as Meteor Shower, Solar Storm, Moonquake, Shuttle Explosion, Landslide, Sink Hole, Communications Blackout, Reactor Meltdown, or Apocalypse."
    },
    {
      id: "core-mining",
      title: "Mining",
      category: "core",
      tags: ["mining", "interact", "mission"],
      body: "Mining actions are boosted by Mission Specialists and mining tools such as the Geology Hammer, Heavy Mining Drill, Impact Drill, and Ultrasonic Mining Pick."
    },
    {
      id: "core-ranged",
      title: "Ranged Weapons",
      category: "core",
      tags: ["ranged", "ammo", "weapon"],
      body: "Ranged cards list range, ammo, and attack type. Medical Specialists cannot use ranged weapons; Tech Specialists cannot use rare weapons."
    },
    {
      id: "status-blinded",
      title: "Blinded",
      category: "core",
      tags: ["status", "blinded", "laser", "flare"],
      body: "Blinded is applied by cards such as S8-Laser Pistol and Lunar Flare. Auto-dim Visor prevents a unit from being blinded."
    },
    {
      id: "status-entangled",
      title: "Entangled",
      category: "core",
      tags: ["status", "entangled", "net", "adhesive"],
      body: "Net Rifle and Adhesive Rifle can entangle targets. Use the printed cards to resolve exact area and timing."
    },
    {
      id: "doc-rulebook",
      title: "Полная книга правил",
      category: "core",
      tags: ["pdf", "rulebook"],
      body: "PDF rulebook is included locally under assets/rules/lunar-rulebook.pdf. The source PDF has no reliable text layer, so this first version uses a curated searchable index."
    },
    {
      id: "doc-zvezda",
      title: "Attack on Zvezda scenarios",
      category: "core",
      tags: ["pdf", "scenario", "zvezda"],
      body: "Scenario sheets for Attack on Zvezda are included locally under assets/rules/zvezda-scenarios.pdf."
    }
  ]
};
